language: ruby
rvm:
- 2.4
cache: bundler

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl ca-certificates
  - sudo dpkg -l

before_script:
 - chmod +x ./travis.sh

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
