name: "BSidesVienna"
title: "BSidesVienna"
description: "BSidesVienna"
url: https://bsidesvienna.at

quiet: false
verbose: true
strict_front_matter: true

# data about the current event for google
evt_year: "2026"
evt_year_hex: "7EA"
evt_startdate: "2026-??-??T10:00:00+02:00"
evt_enddate: "2026-??-??T04:00:00+02:00"
evt_loc_name: "Urania Dachsaal"
evt_loc_address: "Uraniastraße 1"
evt_loc_zip: "1010"
evt_loc_city: "Vienna"

markdown: kramdown
permalink: pretty
highlighter: rouge

exclude:
  [CNAME, README.md, LICENSE, vendor, .gitignore, .github, Gemfile, docker-compose.yml]

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
