name: "BSidesVienna"
description: "BSidesVienna"
year: 2014

markdown: rdiscount
permalink: pretty
highlighter: pygments

exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md]

gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
