name: "BSidesVienna"
title: "BSidesVienna"
description: "BSidesVienna"
archives: [2014, 2015, 2016, 2017, 2019, 2022, 2023]
url: https://bsidesvienna.at

# data about the current event for google
evt_year: "2024"
evt_year_hex: "7E8"
evt_startdate: "TBD"
evt_enddate: "TBD"
evt_loc_name: "TBD"
evt_loc_address: ""
evt_loc_zip: "TBD"
evt_loc_city: "Vienna"

markdown: kramdown
permalink: pretty
highlighter: rouge

exclude: [CNAME, Readme.md, vendor, .gitignore]

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
