name: "BSidesVienna"
description: "BSidesVienna"
year: 2014

#url: "http://bsidesvienna.at"
url: "http://localhost:4000"

markdown: rdiscount
permalink: pretty
pygments: true

exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md]

gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
