name: "BSidesVienna"
description: "BSidesVienna"
archives: [2014, 2015, 2016]
url: https://bsidesvienna.at

markdown: kramdown
permalink: pretty
highlighter: rouge

exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md, vendor, travis.sh]

gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
